# Authors: @Ronald
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: my-agent-pool
  vmImage: 'SVBNVSTGAPP01'
  demands: maven, Agent.Version -gtVersion 2.163.1
  

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml      
    displayName: 'Run a multi-line script'
  
    

  - task: Maven@3
    displayName: 'Run Serenity tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      options: '-Dcucumber.features=src/test/resources/features/ -Dcucumber.filter.tags=@ValidarInicioSesionUsuario -Dcucumber.plugin=json:target/site/result.json -Dcucumber.glue=com.atlantic'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
  
      
    