# Authors: @Ronald
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
pool:
  vmImage: ubuntu-latest

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml      
    displayName: 'Run a multi-line script'
  
    

  - task: Maven@3
    displayName: 'Run Cucumber tests'
    inputs:
      mavenPomFile: 'pom.xml'  # Ruta al archivo pom.xml si no está en el directorio raíz
      goals: 'test'  # El objetivo de Maven que se va a ejecutar
      options: '-Dcucumber.features=src/test/resources/features/ -Dcucumber.filter.tags=@ValidarInicioSesionUsuario -Dcucumber.plugin=json:target/site/result.json -Dcucumber.glue=com.atlantic'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'

      
